version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: banaliz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  bot:
    build: .
    command: ["python", "-m", "src.bot"]
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
volumes:
  pgdata:
